version: '3.4'

services:
  beautysalon.booking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=4680
      - ASPNETCORE_HTTPS_PORTS=4681
    ports:
      - "4680:4680"
      - "4681:4681"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro